### ISSUE TITLE
Messages Recommendation

### ISSUE THREAD

**Issue by curly60e** [fusion44/sendmany#2]
There is possible to add notifications for messages without using Google Services, similar to Signal system.

**Comment by fusion44** [comment]
I need to look at how Signal implements notifications. I'm just not sure yet when I'll be able to work on this.

**Comment by fusion44** [comment]
Seems like Signal is actually using GCM when available. They've implemented a fallback to polling the server when the Google Play Services are not available. I have something similar in mind, but I think I'll implement this a little differently as I need to do this on iOS as well.

**Comment by curly60e** [comment]
> Seems like Signal is actually using GCM when available. They've implemented a fallback to polling the server when the Google Play Services are not available. I have something similar in mind, but I think I'll implement this a little differently as I need to do this on iOS as well.

I'm glad you found out a solution haha!

**Comment by fusion44** [comment]
I've implemented notifications the same way as Signal does. Actually works quite well. In best case I can poll every 15 minutes to get notifications. On iPhones this interval is longer.

Next step would be to introduce a permanent notification to be able to keep a constant connection to LND. Telegram has an option for this. This must be optional, as it consumes quite a bit of battery.
